In [2]:
import pandas as pd
import time
import ast
df = pd.read_csv("data/all_fpl_data.csv")
df.head()

,del,match_id,season,gameweek,team,side,player_id,pos,mins,goals,assists,clean_sheet,shot_saves,pen_saves,pen_misses,goals_conceded,yellow_cards,red_cards,own_goals
0,0,5573,06/07,1,H,Sheffield United,3222,M,90,0,0,False,0,0,0,1,0,0,0
1,1,5573,06/07,1,H,Sheffield United,3215,D,90,0,0,False,0,0,0,1,0,0,0
2,2,5573,06/07,1,H,Sheffield United,3213,D,90,0,0,False,0,0,0,1,0,0,0
3,3,5573,06/07,1,H,Sheffield United,2830,F,87,1,0,False,0,0,0,1,0,0,0
4,4,5573,06/07,1,H,Sheffield United,1725,F,90,0,0,False,0,0,0,1,0,0,0

In [3]:
df.drop("del",inplace=True,axis=1)
df.head()

,match_id,season,gameweek,team,side,player_id,pos,mins,goals,assists,clean_sheet,shot_saves,pen_saves,pen_misses,goals_conceded,yellow_cards,red_cards,own_goals
0,5573,06/07,1,H,Sheffield United,3222,M,90,0,0,False,0,0,0,1,0,0,0
1,5573,06/07,1,H,Sheffield United,3215,D,90,0,0,False,0,0,0,1,0,0,0
2,5573,06/07,1,H,Sheffield United,3213,D,90,0,0,False,0,0,0,1,0,0,0
3,5573,06/07,1,H,Sheffield United,2830,F,87,1,0,False,0,0,0,1,0,0,0
4,5573,06/07,1,H,Sheffield United,1725,F,90,0,0,False,0,0,0,1,0,0,0

In [28]:
def calculate_fpl_points(row):
    total_points = 0
    played_points = calculate_played_points(int(row["mins"]))
    total_points += played_points
    
    goals_points = calculate_goals_points(int(row["goals"]),str(row["pos"]))
    total_points += goals_points
    
    assist_points = calculate_assist_points(int(row["assists"]))
    total_points += assist_points
    
    clean_sheet_points = calculate_clean_sheet_points(str(row["clean_sheet"]),str(row["pos"]))
    total_points += clean_sheet_points
    
    penalty_save_points = calculate_pen_save_points(int(row["pen_saves"]),str(row["pos"]))
    total_points += penalty_save_points
    
    penalty_miss_points = calculate_pen_miss_points(int(row["pen_misses"]))
    total_points -= penalty_miss_points
    
    goals_conceded_points = calculate_goals_conceded_points(int(row["goals_conceded"]),str(row["pos"]))
    total_points -= goals_conceded_points
    
    yellow_card_points = calculate_yellow_card_points(int(row["yellow_cards"]))
    total_points -= yellow_card_points
    
    red_card_points = calculate_red_card_points(int(row["red_cards"]))
    total_points -= red_card_points
    
    own_goal_points = calculate_own_goal_points(int(row["own_goals"]))
    total_points -= own_goal_points
    
    return total_points

In [33]:
def calculate_played_points(mins):
    if mins >= 60:
        return 2
    elif mins == 0:
        return 0
    else:
        return 1

def calculate_goals_points(goals,pos):
    if pos == "F":
        return 4*goals
    elif pos == "M":
        return 5*goals
    else:
        return 6*goals
    
def calculate_assist_points(assists):
    return assists*3
    
def calculate_clean_sheet_points(clean_sheet,pos):
    if pos == "G" or pos == "D":
        if clean_sheet == "True":
            return 4
        else:
            return 0
    elif pos == "M":
        if clean_sheet == "True":
            return 1
        else:
            return 0
    else:
        return 0
    
def calculate_pen_save_points(saves,pos):
    if pos == "G":
        return saves*5
    else:
        return 0
    
def calculate_pen_miss_points(misses):
    return misses*2
    
def calculate_goals_conceded_points(goals_conceded,pos):
    if pos == "G" or pos == "D":
        points = int(goals_conceded/2)
        return points
    else:
        return 0
    
def calculate_yellow_card_points(cards):
    return cards
    
def calculate_red_card_points(cards):
    return cards*3
    
def calculate_own_goal_points(own_goals):
    return own_goals*2

In [34]:
df["points"] = df.apply(calculate_fpl_points,axis=1)

In [35]:
df.to_csv("data/all_fpl_points.csv",index=False)

In [36]:
df.head(30)

,match_id,season,gameweek,team,side,player_id,pos,mins,goals,assists,clean_sheet,shot_saves,pen_saves,pen_misses,goals_conceded,yellow_cards,red_cards,own_goals,points
0,5573,06/07,1,H,Sheffield United,3222,M,90,0,0,False,0,0,0,1,0,0,0,2
1,5573,06/07,1,H,Sheffield United,3215,D,90,0,0,False,0,0,0,1,0,0,0,2
2,5573,06/07,1,H,Sheffield United,3213,D,90,0,0,False,0,0,0,1,0,0,0,2
3,5573,06/07,1,H,Sheffield United,2830,F,87,1,0,False,0,0,0,1,0,0,0,6
4,5573,06/07,1,H,Sheffield United,1725,F,90,0,0,False,0,0,0,1,0,0,0,2
5,5573,06/07,1,H,Sheffield United,3223,M,90,0,0,False,0,0,0,1,0,0,0,2
6,5573,06/07,1,H,Sheffield United,1313,D,90,0,0,False,0,0,0,1,1,0,0,1
7,5573,06/07,1,H,Sheffield United,1613,D,75,0,0,False,0,0,0,1,0,0,0,2
8,5573,06/07,1,H,Sheffield United,3210,G,90,0,0,False,0,0,0,1,0,0,0,2
9,5573,06/07,1,H,Sheffield United,181,D,90,0,1,False,0,0,0,1,0,0,0,5
10,5573,06/07,1,H,Sheffield United,3302,M,60,0,0,False,0,0,0,1,0,0,0,2
11,5573,06/07,1,H,Sheffield United,329,M,30,0,0,False,0,0,0,1,0,0,0,1
12,5573,06/07,1,H,Sheffield United,734,F,3,0,0,False,0,0,0,1,0,0,0,1
13,5573,06/07,1,H,Sheffield United,2668,M,15,0,0,False,0,0,0,1,0,0,0,1
14,5573,06/07,1,A,Liverpool,3126,D,90,0,0,False,0,0,0,1,0,0,0,2
15,5573,06/07,1,A,Liverpool,2915,D,90,0,0,False,0,0,0,1,1,0,0,1
16,5573,06/07,1,A,Liverpool,277,F,83,1,0,False,0,0,0,1,0,0,0,6
17,5573,06/07,1,A,Liverpool,915,D,35,0,0,False,0,0,0,1,0,0,0,1
18,5573,06/07,1,A,Liverpool,2911,G,90,0,0,False,0,0,0,1,0,0,0,2
19,5573,06/07,1,A,Liverpool,1710,D,90,0,0,False,0,0,0,1,0,0,0,2
20,5573,06/07,1,A,Liverpool,2110,D,26,0,0,False,0,0,0,1,0,0,0,1
21,5573,06/07,1,A,Liverpool,2921,M,90,0,0,False,0,0,0,1,1,0,0,1
22,5573,06/07,1,A,Liverpool,1575,M,90,0,0,False,0,0,0,1,0,0,0,2
23,5573,06/07,1,A,Liverpool,2056,M,90,0,0,False,0,0,0,1,0,0,0,2
24,5573,06/07,1,A,Liverpool,1869,F,90,0,0,False,0,0,0,1,0,0,0,2
25,5573,06/07,1,A,Liverpool,2916,D,55,0,0,False,0,0,0,1,0,0,0,1
26,5573,06/07,1,A,Liverpool,2920,M,64,0,0,False,0,0,0,1,0,0,0,2
27,5573,06/07,1,A,Liverpool,1495,M,7,0,0,False,0,0,0,1,0,0,0,1
28,5567,06/07,1,H,Arsenal,2609,D,90,0,0,False,0,0,0,1,0,0,0,2
29,5567,06/07,1,H,Arsenal,2165,M,90,1,0,False,0,0,0,1,0,0,0,7

(10474, 19)

(10474, 3)